spring.application.name=lab304_new
spring.datasource.url=jdbc:postgresql://localhost:5432/example304
spring.datasource.username=postgres
spring.datasource.password=maitien594
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
